name: CI
on: [pull_request, push]
permissions:
  contents: write
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    container: 
      image: elementary/docker:unstable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: apt-get update && apt-get -y install libvala-dev valac meson libsoup-3.0-dev libarchive-dev
      - name: Build
        run: meson build -Dbuild-tests=true -Ddemos=true && ninja -C build
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: libcatalyst
          path: ./
  Test:
    name: Test Build
    runs-on: ubuntu-latest
    needs: Build
    container: 
      image: elementary/docker:unstable
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get -y install libvala-dev valac meson libsoup-3.0-dev libarchive-dev
      - name: Download
        uses: actions/download-artifact@v1
        with:
          name: libcatalyst
          path: ./
      - name: Set Permissions
        run: chmod +x ./build/lib/libcatalyst-1.so*
      - name: Test
        run: ninja -C build test
  Valadoc:
    name: Deploy Valadoc
    runs-on: ubuntu-latest
    needs: Test
    container: 
      image: elementary/docker:unstable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: apt-get update && apt-get -y install libvala-dev valac meson libsoup-3.0-dev libarchive-dev git
      - name: Build
        run: meson build -Ddocumentation=true && ninja -C build
      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/doc/catalyst-1-vala