name: Valadoc
on:
  push:
    branches:
      - master
jobs: 
  Valadoc:
    name: Deploy Valadoc
    runs-on: ubuntu-latest
    container: 
      image: elementary/docker:unstable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: apt-get update && apt-get -y install libvala-dev valac meson libsoup2.4-dev libarchive-dev git
      - name: Build
        run: meson build -Ddocumentation=true && ninja -C build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build/doc/catalyst-1-vala/