name: Valadoc
on:
  push:
    branches:
      - master
jobs: 
  Valadoc:
    name: Deploy Valadoc
    runs-on: ubuntu-latest
    container: 
      image: elementary/docker:unstable
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get -y install libvala-dev valac meson libsoup2.4-dev libarchive-dev
      - name: Build
        run: meson build && ninja -C build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: build/doc/catalyst-1-vala/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}